#
#   ___           _   _    __  __
#  |   \ ___ __ _| |_| |_ |  \/  |___ _ _  ___ _  _
#  | |) / -_) _` |  _| ' \| |\/| / _ \ ' \/ -_) || |
#  |___/\___\__,_|\__|_||_|_|  |_\___/_||_\___|\_, |
#                                              |__/
#                        created by GalaxyVN
#
#      A plugin to enhance the survival, skyblock gameplay aspect
#           and bring a hardcore mode for players :)
#

general:
  check-for-updates: true
  notify-update-join: true

global:
  money:
    # Khi chết sẽ mất 50% số tiền hiện tại
    drop-percent: 50
    # Bật tắt gửi tin nhắn
    message-enabled: true
    title:
      enabled: true
      fade-in: 5
      stay-in: 10
      fade-out: 5
    actionbar:
      enabled: true
      duration: 5

  heart:
    # Kiểm tra máu để thông báo
    heart-check: 3
    # Bật tắt gửi tin nhắn
    title:
      enabled: true
      fade-in: 5
      stay-in: 10
      fade-out: 5